id: P010539
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W2DB57569
  title: བློ་སྦྱོང་དོན་བདུན་མའི་སྙིང་པོ
  author: ''
  volumes:
    64ee458e48e04388ba031b471260203e:
      image_group_id: I2DB57596
      title: ''
      volume_number: 1
      total_pages: 746
      base_file: v001.txt
